apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "admin-user" to access the whole content of the cluster.
kind: ClusterRoleBinding
metadata:
  name: admin-user
subjects:
- kind: ServiceAccount
  name: admin-user # Name is case sensitive
  namespace: kubernetes-dashboard
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io